# docker version
version: "3.8"

services:
  Backend_Frontend:
    image: quay.io/keycloak/keycloak:20.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_svr
      KC_DB_URL_DATABASE: shuttle-keycloak
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9000:8080"
    depends_on:
      shuttledb:
        condition: service_healthy
      postgres_svr:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: "172.25.0.2"

  postgres_svr:
    image: postgres:10
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: shuttle-keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    networks:
      network_sso:
        ipv4_address: "172.25.0.3"

  shuttledb:
    image: postgres:10
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: shuttledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - "5433:5432"
    networks:
      network_sso:
        ipv4_address: "172.25.0.4"
networks:
  network_sso:
    driver: bridge
    ipam:
      # IP Address management
      driver: default
      # default = bridge
      config:
        - subnet: "172.25.0.0/16"
