spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shuttledb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/keys
          issuer-uri: http://localhost:8080/oauth2/token
jwt:
  # TODO: REPLACE WITH YOUR OWN SECRET KEY
  key: 357638792F423F4528482B4D6251655468576D5A7133743677397A2443264629
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000