spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shuttledb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          mykeycloak:
            client-id: shuttle-login
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "localhost:9000/login/oauth2/code/ShuttleDev"
          google:
            client-id:
            client-secret:
            scope:
              - email
              - openid
        provider:
          mykeycloak:
            jwk-set-uri: http://localhost:9000/realms/ShuttleDev/protocol/openid-connect/certs
            user-info-uri: http://localhost:9000/realms/ShuttleDev/protocol/openid-connect/userinfo
            authorization-uri: http://localhost:9000/realms/ShuttleDev/protocol/openid-connect/auth
            token-uri: http://localhost:9000/realms/ShuttleDev/protocol/openid-connect/token
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/ShuttleDev
          jwk-set-uri: http://localhost:9000/realms/ShuttleDev/protocol/openid-connect/certs
jwt:
  key: 357638792F423F4528482B4D6251655468576D5A7133743677397A2443264629
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
